# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: skills
    url: /#skills
    weight: 11
  - name: hobbies
    url: /#hobbies
    weight: 12
  - name: Experience
    url: experience/
    weight: 20
  - identifier: Projects
    name: Projects
    weight: 30
  - name: Contact
    url: Contact
    weight: 40

  # Projects 서브 탭을 추가
  - name: Java
    url: projects/Java
    parent: Projects
    weight: 31
  - name: WebService
    url: projects/WebService
    parent: "Projects"  
    weight: 32
  - name: SE
    url: projects/SE
    parent: "Projects"
    weight: 33